modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="calubs_materials_end_addon"
version="0.0.1"
displayName="Calub's Materials - End Addon"
credits="Created by Calub and Razzkelfatzz"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Calub. Razzkelfatzz"
description='''
An addon for Calubs Materials that adds materials in The End
'''

[[dependencies.calubs_materials_end_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




